import 'package:flutter/material.dart';

class AgtonomyIcons {
  AgtonomyIcons._();

  static const _kFontFam = 'AgtonomyIcons';
  static const String? _kFontPkg = null;

  static const IconData snail = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData turtle = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rabbit = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheetah = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorFaults = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noBusConnection = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData busConnection = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interlock = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noLocation = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knownLocation = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepadConnection = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractor = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowLeft = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowRight = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floatFront = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floatRear = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cruise = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourGlass = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pto = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lights = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData routeOutlined = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData update = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restart = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData batteryUpright = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData energy = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liftFront = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liftBack = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volts = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractorRear = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery0 = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery1 = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery2 = IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery3 = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery4 = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery5 = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery6 = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData batteryFull = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData batteryCharging = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pitchUp = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pitchDown = IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pitchLevel = IconData(0xe83B, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rollRight = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rollLeft = IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rollLevel = IconData(0xe83C, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frontHand = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seatSwitch = IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aux = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData superscriptPercentage = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compassUnlocked = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compassLocked = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
